# Generated by Django 5.0.3 on 2024-03-25 19:56
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('linkedin_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=64)),
                ('overview', models.CharField(max_length=1024)),
                ('responsibilities', models.CharField(max_length=1024)),
                ('qualifications', models.CharField(max_length=1024)),
                ('work_site', models.CharField(max_length=64)),
                ('work_type', models.CharField(max_length=64)),
                ('is_open', models.BooleanField()),
                ('posted_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobScreenInterviews',
            fields=[
                ('job_screen_interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('are_candidates_notified', models.BooleanField()),
                ('are_all_interviews_done', models.BooleanField()),
                ('last_interveiw_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileScore',
            fields=[
                ('profile_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_score', models.IntegerField()),
                ('relevance_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_file', models.CharField(max_length=256)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.candidates')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.jobs')),
                ('profile_score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.profilescore')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateInterviews',
            fields=[
                ('canditate_interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_date', models.DateTimeField()),
                ('interview_time', models.TimeField()),
                ('candidate_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.candidateapplications')),
                ('job_screen_interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.jobscreeninterviews')),
            ],
        ),
        migrations.CreateModel(
            name='JobScreens',
            fields=[
                ('job_screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_number', models.IntegerField()),
                ('last_screen', models.BooleanField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.jobs')),
            ],
        ),
        migrations.AddField(
            model_name='jobscreeninterviews',
            name='job_screen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.jobscreens'),
        ),
        migrations.CreateModel(
            name='CandidateJobScreenRelations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_screen_passed', models.BooleanField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.candidateapplications')),
                ('job_screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.jobscreens')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('notif_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('is_email_notif', models.BooleanField()),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.accounttypes')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.organizations'),
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.organizations')),
            ],
        ),
        migrations.AddField(
            model_name='organizations',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.recruiters'),
        ),
        migrations.AddField(
            model_name='jobscreeninterviews',
            name='creater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.recruiters'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='creater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.recruiters'),
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_job_screen_relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.candidatejobscreenrelations')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.recruiters')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.salaries'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('profile_picture', models.CharField(max_length=256)),
                ('timezone', models.CharField(max_length=256)),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.accounttypes')),
            ],
        ),
        migrations.AddField(
            model_name='recruiters',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.users'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type_id', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('creation_time', models.TimeField()),
                ('additional_info', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.users')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.users'),
        ),
    ]
