# Generated by Django 5.0.4 on 2024-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0002_alter_organization_org_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_setup",
            field=models.BooleanField(default=False),
        ),
    ]
