# Generated by Django 5.0.4 on 2024-04-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_notification_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user_id',
        ),
    ]
