# Generated by Django 5.0.4 on 2024-04-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0004_alter_organization_org_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilescore",
            name="relevance_score",
        ),
    ]
