# Generated by Django 5.0.4 on 2024-04-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_remove_candidate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.organization', to_field='org_name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats.organization', to_field='org_name', unique=True),
        ),
    ]
