# Generated by Django 5.0.4 on 2024-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_alter_job_org_id_alter_organization_org_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admin_id',
        ),
    ]
