# Generated by Django 5.0.4 on 2024-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0005_remove_profilescore_relevance_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="overview",
        ),
        migrations.AddField(
            model_name="job",
            name="job_description",
            field=models.TextField(default="JOB DESCRIPTION DEFAULT VALUE"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.CharField(
                default="Software Enginneering", max_length=256, null=True
            ),
        ),
    ]
