# Generated by Django 5.0.4 on 2024-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0006_remove_job_overview_job_job_description_job_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(null=True),
        ),
    ]
