# Generated by Django 5.0.4 on 2024-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_remove_organization_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
