# Generated by Django 5.0.4 on 2024-04-28 10:01

import ats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0008_alter_recruiter_org_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateapplication",
            name="resume_file",
            field=models.FileField(upload_to=ats.models.resume_filename),
        ),
    ]
