# Generated by Django 5.0.4 on 2024-04-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0009_candidateapplication_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='org_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ats.organization', to_field='org_name'),
        ),
    ]
