# Generated by Django 5.0.4 on 2024-04-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0009_alter_candidateapplication_resume_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilescore",
            name="candidate_application_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ats.candidateapplication",
            ),
            preserve_default=False,
        ),
    ]
