# Generated by Django 5.0.4 on 2024-04-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0010_profilescore_candidate_application_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateapplication",
            name="profile_score_id",
        ),
    ]
