# Generated by Django 5.0.4 on 2024-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0011_alter_recruiter_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='overview',
            field=models.CharField(max_length=5000),
        ),
    ]
